<a href="https://colab.research.google.com/github/andria03/Rajagiri-Python-files/blob/main/Module3_NumPy_Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**UPLOADING FILES TO GOOGLE COLAB**

In [ ]:
from google.colab import files
supermarket=files.upload()

Saving players_20.csv to players_20.csv


In [ ]:
import google,colab
dir(google.colab)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_debugpy',
 '_debugpy_repr',
 '_history',
 '_import_hooks',
 '_import_magics',
 '_inspector',
 '_installation_commands',
 '_interactive_table_helper',
 '_interactive_table_hint_button',
 '_ipython',
 '_jupyter_nbextension_paths',
 '_kernel',
 '_message',
 '_pip',
 '_reprs',
 '_shell',
 '_shell_customizations',
 '_system_commands',
 '_tensorflow_magics',
 '_variable_inspector',
 'auth',
 'data_table',
 'drive',
 'errors',
 'files',
 'load_ipython_extension',
 'output',
 'runtime',
 'snippets',
 'widgets']


# **PANDAS**
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.
Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.



In [ ]:
import pandas

***CREATING DATAFRAME FROM DICTIONARY***

In [ ]:
teamgoals={
    'teams':['Spain','England'],
    'goals':[2,4]
}
teamgoaldf= pandas.DataFrame(teamgoals)
print(teamgoaldf)

     teams  goals
0    Spain      2
1  England      4


***READING AND DISPLAYING CSV FILES AS DATAFRAMES***

In [ ]:
import pandas
dataframe=pandas.read_csv("Supermarket_sales.csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

***DISPLAYING ONLY THE FIRST 5 ROWS OF THE DATAFRAME***

---



In [ ]:
print(dataframe.head())

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty      58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel      86.31         7  30.2085  634.3785   2/8/2019   

    Time      Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0  13:08      Ewallet  522.83                 4.761905        26.1415   

***DISPLAYING FIRST n number of ROWS***

In [ ]:
print(dataframe.head(10))

NameError: ignored

***DISPLAYING ONLY THE LAST 5 ROWS OF THE DATAFRAME***

In [ ]:
print(dataframe.tail())

       No    InvoiceID Branch       City Customertype  Gender  \
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

             Productline  Unitprice  Quantity      Tax      Total       Date  \
995    Health and beauty      40.35         1   2.0175    42.3675  1/29/2019   
996   Home and lifestyle      97.38        10  48.6900  1022.4900   3/2/2019   
997   Food and beverages      31.84         1   1.5920    33.4320   2/9/2019   
998   Home and lifestyle      65.82         1   3.2910    69.1110  2/22/2019   
999  Fashion accessories      88.34         7  30.9190   649.2990  2/18/2019   

      Time  Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
995  13:46  Ewallet   40.35                 4.7619

T

**DIAPLAYING SPECIFIC COLUMN**

In [ ]:
print(dataframe[['City'],['Branch']])

***TO VIEW THE INDEX OF THE DATAFRAME***

In [ ]:
print(dataframe.index)

RangeIndex(start=0, stop=1000, step=1)


In [ ]:
for i in dataframe.index:
  print(dataframe.City[i],dataframe.Branch[i])

***UPLOADING FIFA DATA***

In [ ]:
import pandas



***PRINTING DATA WITH A MAX VALUE***

In [ ]:
fifadataframe = pandas.read_csv("players_20.csv")
max_overall=fifadataframe.age.idxmax()
#max_overall_loc = fifadataframe.overall.idxmax()
#person=fifadataframe.loc[max_overall_loc]
print(max_overall)
#print(person.long_name," has the highest overall of ",max_overall)

11832


In [ ]:
print(fifadataframe.head(10))

   sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2     190871  https://sofifa.com/player/190871/neymar-da-sil...   
3     200389  https://sofifa.com/player/200389/jan-oblak/20/...   
4     183277  https://sofifa.com/player/183277/eden-hazard/2...   
5     192985  https://sofifa.com/player/192985/kevin-de-bruy...   
6     192448  https://sofifa.com/player/192448/marc-andre-te...   
7     203376  https://sofifa.com/player/203376/virgil-van-di...   
8     177003  https://sofifa.com/player/177003/luka-modric/2...   
9     209331  https://sofifa.com/player/209331/mohamed-salah...   

          short_name                            long_name  age         dob  \
0           L. Messi       Lionel Andrés Messi Cuccittini   32  1987-06-24   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   34  1985-02-05   
2          Neymar Jr        

***PRINTING DATA WITH MIN VALUE***

In [ ]:
min_age=fifadataframe.age.min()
min_age_loc = fifadataframe.age.idxmin()
person=fifadataframe.loc[min_age_loc]


print(person.long_name," is the youngest of all players "," . His age is ",person.age)

Adam Hložek  is the youngest of all players   . His age is  16


***PRINTING THE COUNT OF ENTIRE ROWS***

In [ ]:
playercount = fifadataframe.sofifa_id.count()
print(playercount)

18278


***PRINTING THE AVERAGE OF A SPECIFIC COLUMN***

In [ ]:
overall_average = fifadataframe.overall.mean()
print(overall_average)

66.24499398183609


***PRINTING THE PLAYERS OF A SPECIFIC TEAM***

In [ ]:
for i in fifadataframe.index:
  if fifadataframe.club[i] == "FC Barcelona":
    print(fifadataframe.short_name[i])

L. Messi
M. ter Stegen
L. Suárez
Sergio Busquets
A. Griezmann
Piqué
Jordi Alba
S. Umtiti
I. Rakitić
F. de Jong
C. Lenglet
Neto
O. Dembélé
Arthur
A. Vidal
Nélson Semedo
Sergi Roberto
Rafinha
Junior Firpo
Aleñá
Riqui Puig
J. Todibo
M. Wagué
H. Abe
L. Reis
Abel Ruiz
Oriol Busquets
Carles Pérez
Miranda
Chumi
Álex Collado
Jorge Cuenca
Iñaki Peña


***COUNTING PLAYERS FROM DIFFERENT COUNTRIES***

In [ ]:
fifadataframe.groupby('nationality').count()

sofifa_id  player_url  short_name  long_name  age  dob  \
nationality                                                                 
Afghanistan                2           2           2          2    2    2   
Albania                   43          43          43         43   43   43   
Algeria                   50          50          50         50   50   50   
Angola                    16          16          16         16   16   16   
Antigua & Barbuda          7           7           7          7    7    7   
...                      ...         ...         ...        ...  ...  ...   
Venezuela                 66          66          66         66   66   66   
Vietnam                    1           1           1          1    1    1   
Wales                    117         117         117        117  117  117   
Zambia                    10          10          10         10   10   10   
Zimbabwe                  12          12          12         12   12   12   

                   height_cm  weight_kg  club  overall  ...  lwb  ldm  cdm  \
nationality                                             ...                  
Afghanistan                2          2     2        2  ...    2    2    2   
Albania                   43         43    43       43  ...   40   40   40   
Algeria                   50         50    50       50  ...   43   43   43   
Angola                    16         16    16       16  ...   16   16   16   
Antigua & Barbuda          7          7     7        7  ...    7    7    7   
...                      ...        ...   ...      ...  ...  ...  ...  ...   
Venezuela                 66         66    66       66  ...   61   61   61   
Vietnam                    1          1     1        1  ...    1    1    1   
Wales                    117        117   117      117  ...  103  103  103   
Zambia                    10         10    10       10  ...   10   10   10   
Zimbabwe                  12         12    12       12  ...   12   12   12   

                   rdm  rwb   lb  lcb   cb  rcb   rb  
nationality                                           
Afghanistan          2    2    2    2    2    2    2  
Albania             40   40   40   40   40   40   40  
Algeria             43   43   43   43   43   43   43  
Angola              16   16   16   16   16   16   16  
Antigua & Barbuda    7    7    7    7    7    7    7  
...                ...  ...  ...  ...  ...  ...  ...  
Venezuela           61   61   61   61   61   61   61  
Vietnam              1    1    1    1    1    1    1  
Wales              103  103  103  103  103  103  103  
Zambia              10   10   10   10   10   10   10  
Zimbabwe            12   12   12   12   12   12   12  

[162 rows x 103 columns]

***DISPLAYING THE DETAILS OF PLAYERS OF CERTIAN TEAM***

In [ ]:
fifadataframe.loc[fifadataframe['club'] == "FC Barcelona"]

sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...   
6         192448  https://sofifa.com/player/192448/marc-andre-te...   
19        176580  https://sofifa.com/player/176580/luis-suarez/2...   
21        189511  https://sofifa.com/player/189511/sergio-busque...   
22        194765  https://sofifa.com/player/194765/antoine-griez...   
29        152729  https://sofifa.com/player/152729/gerard-pique-...   
51        189332  https://sofifa.com/player/189332/jordi-alba-ra...   
59        205600  https://sofifa.com/player/205600/samuel-umtiti...   
64        168651  https://sofifa.com/player/168651/ivan-rakitic/...   
75        228702  https://sofifa.com/player/228702/frenkie-de-jo...   
84        220440  https://sofifa.com/player/220440/clement-lengl...   
91        194404  https://sofifa.com/player/194404/norberto-mura...   
110       231443  https://sofifa.com/player/231443/ousmane-dembe...   
115       230658  https://sofifa.com/player/230658/arthur-henriq...   
142       181872  https://sofifa.com/player/181872/arturo-vidal/...   
249       227928  https://sofifa.com/player/227928/nelson-cabral...   
274       199564  https://sofifa.com/player/199564/sergio-robert...   
344       201400  https://sofifa.com/player/201400/rafael-alcant...   
602       241184  https://sofifa.com/player/241184/hector-junior...   
1276      233113  https://sofifa.com/player/233113/carles-alena-...   
4042      242816  https://sofifa.com/player/242816/ricard-puig-m...   
4045      245388  https://sofifa.com/player/245388/jean-clair-to...   
4068      237156  https://sofifa.com/player/237156/moussa-wague/...   
4780      237823  https://sofifa.com/player/237823/hiroki-abe/20...   
4781      240683  https://sofifa.com/player/240683/ludovit-reis/...   
6634      239250  https://sofifa.com/player/239250/abel-ruiz-ort...   
7711      239249  https://sofifa.com/player/239249/oriol-busquet...   
7712      240654  https://sofifa.com/player/240654/carles-perez-...   
7713      240915  https://sofifa.com/player/240915/juan-miranda-...   
9908      241810  https://sofifa.com/player/241810/juan-brandari...   
9938      242999  https://sofifa.com/player/242999/alex-collado-...   
9970      237522  https://sofifa.com/player/237522/jorge-cuenca-...   
11042     246139  https://sofifa.com/player/246139/ignacio-pena-...   

            short_name                            long_name  age         dob  \
0             L. Messi       Lionel Andrés Messi Cuccittini   32  1987-06-24   
6        M. ter Stegen                Marc-André ter Stegen   27  1992-04-30   
19           L. Suárez             Luis Alberto Suárez Díaz   32  1987-01-24   
21     Sergio Busquets             Sergio Busquets i Burgos   30  1988-07-16   
22        A. Griezmann                    Antoine Griezmann   28  1991-03-21   
29               Piqué                Gerard Piqué Bernabéu   32  1987-02-02   
51          Jordi Alba                     Jordi Alba Ramos   30  1989-03-21   
59           S. Umtiti                        Samuel Umtiti   25  1993-11-14   
64          I. Rakitić                         Ivan Rakitić   31  1988-03-10   
75          F. de Jong                      Frenkie de Jong   22  1997-05-12   
84          C. Lenglet                      Clément Lenglet   24  1995-06-17   
91                Neto                 Norberto Murara Neto   29  1989-07-19   
110         O. Dembélé                      Ousmane Dembélé   22  1997-05-15   
115             Arthur  Arthur Henrique Ramos Oliveira Melo   22  1996-08-12   
142           A. Vidal                         Arturo Vidal   32  1987-05-22   
249      Nélson Semedo                 Nélson Cabral Semedo   25  1993-11-16   
274      Sergi Roberto              Sergio Roberto Carnicer   27  1992-02-07   
344            Rafinha       Rafael Alcântara do Nascimento   26  1993-02-12   
602       Junior Firpo           Héctor Junior Firpo Adamés   22  1996-0

***PRINTING THE MAX PERFORMANCE VALUE OF A GIVEN CLUB***

In [ ]:
fifadataframe['overall'].loc[fifadataframe['club'] == "FC Barcelona"].max()

94

***DROPING SPECIFIC COLUMN***

In [ ]:
print(fifadataframe.head())
fifadataframe.drop(['lwb'],axis=1)

   sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2     190871  https://sofifa.com/player/190871/neymar-da-sil...   
3     200389  https://sofifa.com/player/200389/jan-oblak/20/...   
4     183277  https://sofifa.com/player/183277/eden-hazard/2...   

          short_name                            long_name  age         dob  \
0           L. Messi       Lionel Andrés Messi Cuccittini   32  1987-06-24   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   34  1985-02-05   
2          Neymar Jr        Neymar da Silva Santos Junior   27  1992-02-05   
3           J. Oblak                            Jan Oblak   26  1993-01-07   
4          E. Hazard                          Eden Hazard   28  1991-01-07   

   height_cm  weight_kg nationality                 club  ...   lwb   ldm  \
0        170         72   Argentina         FC Barc

sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...   
1          20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2         190871  https://sofifa.com/player/190871/neymar-da-sil...   
3         200389  https://sofifa.com/player/200389/jan-oblak/20/...   
4         183277  https://sofifa.com/player/183277/eden-hazard/2...   
...          ...                                                ...   
18273     245006  https://sofifa.com/player/245006/shuai-shao/20...   
18274     250995  https://sofifa.com/player/250995/mingjie-xiao/...   
18275     252332  https://sofifa.com/player/252332/wei-zhang/20/...   
18276     251110  https://sofifa.com/player/251110/haijian-wang/...   
18277     233449  https://sofifa.com/player/233449/ximing-pan/20...   

              short_name                            long_name  age  \
0               L. Messi       Lionel Andrés Messi Cuccittini   32   
1      Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   34   
2              Neymar Jr        Neymar da Silva Santos Junior   27   
3               J. Oblak                            Jan Oblak   26   
4              E. Hazard                          Eden Hazard   28   
...                  ...                                  ...  ...   
18273         Shao Shuai                                   邵帅   22   
18274       Xiao Mingjie                         Mingjie Xiao   22   
18275          Zhang Wei                                   张威   19   
18276       Wang Haijian                                  汪海健   18   
18277         Pan Ximing                                  潘喜明   26   

              dob  height_cm  weight_kg nationality  \
0      1987-06-24        170         72   Argentina   
1      1985-02-05        187         83    Portugal   
2      1992-02-05        175         68      Brazil   
3      1993-01-07        188         87    Slovenia   
4      1991-01-07        175         74     Belgium   
...           ...        ...        ...         ...   
18273  1997-03-10        186         79    China PR   
18274  1997-01-01        177         66    China PR   
18275  2000-05-16        186         75    China PR   
18276  2000-08-02        185         74    China PR   
18277  1993-01-11        182         78    China PR   

                                club  ...    rm   ldm   cdm   rdm   rwb    lb  \
0                       FC Barcelona  ...  92+2  66+2  66+2  66+2  68+2  63+2   
1                           Juventus  ...  88+3  61+3  61+3  61+3  65+3  61+3   
2                Paris Saint-Germain  ...  89+3  61+3  61+3  61+3  66+3  61+3   
3                    Atlético Madrid  ...   NaN   NaN   NaN   NaN   NaN   NaN   
4                        Real Madrid  ...  89+3  63+3  63+3  63+3  66+3  61+3   
...                              ...  ...   ...   ...   ...   ...   ...   ...   
18273               Beijing Renhe FC  ...  33+2  42+2  42+2  42+2  43+2  45+2   
18274               Shanghai SIPG FC  ...  35+2  43+2  43+2  43+2  44+2  46+2   
18275         Hebei China Fortune FC  ...  45+2  49+2  49+2  49+2  47+2  47+2   
18276  Shanghai Greenland Shenhua FC  ...  46+2  48+2  48+2  48+2  48+2  48+2   
18277         Hebei China Fortune FC  ...  46+2  49+2  49+2  49+2  48+2  48+2   

        lcb    cb   rcb    rb  
0      52+2  52+2  52+2  63+2  
1      53+3  53+3  53+3  61+3  
2      46+3  46+3  46+3  61+3  
3       NaN   NaN   NaN   NaN  
4      49+3  49+3  49+3  61+3  
...     ...   ...   ...   ...  
18273  46+2  46+2  46+2  45+2  
18274  47+2  47+2  47+2  46+2  
18275  49+2  49+2  49+2  47+2  
18276  49+2  49+2  49+2  48+2  
18277  50+2  50+2  50+2  48+2  

[18278 rows x 103 columns]

In [ ]:
print(fifadataframe.head(2))
fifadataframe.drop([5],axis=0)
print("*****")


#**NumPy**

***IMPORTING NUMPY***

In [ ]:
import numpy as np


***CREATING 1dARRAY FROM LIST***

In [ ]:
student_marks_BA=[12,14,10]
marksarray=np.array(student_marks_BA)
print(marksarray)

[12 14 10]


***CREATING ND ARRAY FROM LIST OF LIST***

In [ ]:
import numpy as np
student_marks=[[12,14,10],[15,19,20],[11,15,19]]
marksarray=np.array(student_marks)
print(marksarray)

[[12 14 10]
 [15 19 20]
 [11 15 19]]


***CHECKING THE DIMENSION / SHAPE OF AN EXSISTING ARRAY***

In [ ]:
marksarray.shape

(3, 3)

***CREATING EVENLY SPACED ARRAY USING ARANGE***

In [ ]:
values1= np.arange(20)
print(values1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
values=np.arange(1,11)
print(values)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
values2=np.arange(5,11)
print(values2)

[ 5  6  7  8  9 10]


In [ ]:
values3=np.arange(1,11,2)
print(values3)

[1 3 5 7 9]


***CREATING ZERO ARRAY***

In [ ]:
zeroarray = np.zeros(5)
print(zeroarray)

[0. 0. 0. 0. 0.]


In [ ]:
zeroarray = np.zeros((2,6))
print(zeroarray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


***CREATING ONES ARRAY***

In [ ]:
onesarray=np.ones(5)
print(onesarray)

[1. 1. 1. 1. 1.]


In [ ]:
onesarray2 = np.ones((4,2))
print(onesarray2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


***CREATING 2D IDENTITY MATRIX USING eye()***

In [ ]:
identityarray=np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


***FINDING LENGTH OF ARRAY***

In [ ]:
len(zeroarray)

2

In [ ]:
len(onesarray)


5

In [ ]:
len(onesarray2)

4

***RESHAPING AN ARRAY***

In [ ]:
firstarray=np.array([[10,20,30,40],[2,4,6,8],[5,10,15,20]])
print(firstarray.shape)
secondarray=firstarray.reshape(4,3)
print(firstarray)
print("*****")
print(len(firstarray))
print("*****")
print(secondarray)
third_array=firstarray.reshape(6,2)
print(third_array)

(3, 4)
[[10 20 30 40]
 [ 2  4  6  8]
 [ 5 10 15 20]]
*****
3
*****
[[10 20 30]
 [40  2  4]
 [ 6  8  5]
 [10 15 20]]
[[10 20]
 [30 40]
 [ 2  4]
 [ 6  8]
 [ 5 10]
 [15 20]]


***CREATING AN ARRAY WITH EVENLY SPACED VALUES WITHIN THE RANGE***

In [ ]:
val=np.linspace(1,10)
print(val)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [ ]:
val=np.linspace(1,10,10)
print(val)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
val=np.linspace(1,10,20)
print(val)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


***TO GENERATE RANDOM VALUES BETWEEN O AND 1***

In [ ]:
array=np.random.rand(3,3)
print(array)

[[0.29848783 0.2352203  0.27682941]
 [0.90886021 0.79411967 0.63258742]
 [0.99147448 0.41783798 0.43994322]]


***TO GENERATE RANDOM INTEGER VALUES***

In [ ]:
values=np.random.randint(1,3,5)
print(values)

[1 2 1 1 2]


In [ ]:
values=np.random.randint(1,20,8)
print(values)

[16  4  5  3 10  6 13 14]


In [ ]:
values.reshape(4,2)

array([[16,  4],
       [ 5,  3],
       [10,  6],
       [13, 14]])

In [ ]:
randshaped = np.random.randint(1,20,(5,3))
print(randshaped)

[[14  6 14]
 [17 10 11]
 [16 10  4]
 [10  6  9]
 [18  8  9]]


***ACCESSING VALUES FROM ARRAY USING INDEX***

In [ ]:
values=np.random.randint(10,20,5)
print(values)
print(values[0])

[15 15 10 14 13]
15


In [ ]:
values=np.random.randint(10,20,5)
print(values)
print(values[-1])

[13 11 17 11 16]
16


In [ ]:
values=np.random.randint(10,20,(3,6))
print(values)
print("******")
print(values[0])

[[18 12 16 17 16 17]
 [18 14 12 10 11 13]
 [13 11 10 19 15 15]]
******
[18 12 16 17 16 17]


In [ ]:
values=np.random.randint(10,20,(3,6))
print(values)
print("******")
print(values[-1])

[[17 19 16 17 16 16]
 [17 17 15 17 10 13]
 [10 10 14 11 14 14]]
******
[10 10 14 11 14 14]


In [ ]:
values=np.random.randint(10,20,(6,3))
print(values)
print("******")
print(values[0][1])

[[15 11 10]
 [13 17 18]
 [16 15 10]
 [18 18 14]
 [19 11 16]
 [13 16 18]]
******
11


***ACCESSING ELEMENTS OF A SPECIFIC RANGE***

In [ ]:
print(values[0:2])

[[15 11 10]
 [13 17 18]]


In [ ]:
print(values[:2])

[[15 11 10]
 [13 17 18]]


In [ ]:
print(values[0:])

[[15 11 10]
 [13 17 18]
 [16 15 10]
 [18 18 14]
 [19 11 16]
 [13 16 18]]


In [ ]:
print(values[2:5])

[[16 15 10]
 [18 18 14]
 [19 11 16]]


In [ ]:
print(values[2,2])

10


In [ ]:
print(values[2][2])

10


Specific Row, Only certain column range

In [ ]:
print(values[2,0:2])

[16 15]


Certain row range, selected column

In [ ]:
print(values)
print("*******")
print(values[2:4,1])

[[15 11 10]
 [13 17 18]
 [16 15 10]
 [18 18 14]
 [19 11 16]
 [13 16 18]]
*******
[15 18]


Row in range, Column  in range

In [ ]:
print(values)
print("*******")
print(values[2:4,0:2])

[[15 11 10]
 [13 17 18]
 [16 15 10]
 [18 18 14]
 [19 11 16]
 [13 16 18]]
*******
[[16 15]
 [18 18]]


***CONDITIONAL INDEXING***

In [ ]:
print(values)
print("*******")
print(values>15)

[[15 11 10]
 [13 17 18]
 [16 15 10]
 [18 18 14]
 [19 11 16]
 [13 16 18]]
*******
[[False False False]
 [False  True  True]
 [ True False False]
 [ True  True False]
 [ True False  True]
 [False  True  True]]


In [ ]:
print(values)
print("*******")
print(values[values>15])

[[15 11 10]
 [13 17 18]
 [16 15 10]
 [18 18 14]
 [19 11 16]
 [13 16 18]]
*******
[17 18 16 18 18 19 16 16 18]


In [ ]:
print(values)
print("*******")
values[values>15]=99
print(values)

[[15 11 10]
 [13 99 99]
 [99 15 10]
 [99 99 14]
 [99 11 99]
 [13 99 99]]
*******
[[15 11 10]
 [13 99 99]
 [99 15 10]
 [99 99 14]
 [99 11 99]
 [13 99 99]]


***TO CREATE A COPY OF AN EXISTING ARRAY***

In [ ]:
newvalues= values.copy()
print(values)
print("******")
print(newvalues)

[[15 11 10]
 [13 99 99]
 [99 15 10]
 [99 99 14]
 [99 11 99]
 [13 99 99]]
******
[[15 11 10]
 [13 99 99]
 [99 15 10]
 [99 99 14]
 [99 11 99]
 [13 99 99]]
